### ISSUE TITLE
REQUEST Examples

### ISSUE THREAD

**Issue by JaredSartin** [rxi/juno#1]
Could we get the example shown in the Gif, even if its just that one room? Would love to see more of the parts this framework used together for context.

**Comment by WetDesertRock** [comment]
That can be found here: http://ludumdare.com/compo/ludum-dare-32/?action=preview&uid=16007 (click on the source link)

Perhaps rxi can add a link to this game in the Readme.md though.

**Comment by rxi** [comment]
@WetDesertRock
You just managed to sneak in and respond before I could finish typing!

@JaredSartin 
If you download the game from the link @WetDesertRock provided and extract it there should be a file named `pak0`. This is a .zip containing all the game content and code. The executable file is simply juno itself built normally, which by default attempts to load the game content from the archive named pak0, then pak1, pak2 etc.

**Comment by JaredSartin** [comment]
Awesome! Thanks guys! Now to see if I can grok it all in time for LD!
