### ISSUE TITLE
OSX quitting results in a segfault

### ISSUE THREAD

**Issue by bakpakin** [rxi/juno#6]
On OSX, everything works, but quitting out of the application results in a segfault 100% of the time.

**Comment by WetDesertRock** [comment]
This is due to main.c:32 `atexit(shutdown);` which quits SDL (they in fact warn against doing this in the SDL docs). When I do my OS X builds I comment out this line.

This might make fullscreen not shut down correctly though. Good to have this issue made though.

**Comment by rxi** [comment]
> This is due to main.c:32 atexit(shutdown); which quits SDL (they in fact warn against doing this in the SDL docs). When I do my OS X builds I comment out this line.

The SDL docs  use `atexit()` in their own example of the `SDL_Quit()` function: https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlquit.html

It's hard to diagnose the exact issue myself as I don't have access to a mac. Would one of you would you be able to check if omitting the atexit shutdown() callback still results in a not-crashing/freezing exit if lua audio callbacks are being used in the project -- you may have to do some heavy processing in the callback to increase the chances of it being active on exit, and run the project a fair number of times. You may also need to check the screen resolution is being restored when exiting from fullscreen. If both these cases are fine I'll add an `#ifdef` to omit the shutdown code on OSX.

**Comment by bakpakin** [comment]
Just commented out the `atexit` code, and modified the xytone example to take about a full second per frame in the audio callback. Still does not crash after repeated attempts, so by your logic it should ok to comment out `atexit` on OSX.

**Comment by rxi** [comment]
Commited the change.

If you get a chance could you check to see if everything behaves properly when exiting after being in fullscreen mode? Here's a small test program (press any key to exit):

``` lua
function juno.onLoad()
  juno.graphics.setFullscreen(true)
end

function juno.onKeyDown()
  os.exit()
end

function juno.onDraw()
  juno.graphics.drawText("elapsed: " .. juno.time.getTime(), 20, 20)
end

```

**Comment by WetDesertRock** [comment]
Fullscreen works correctly, however, it doesn't display properly. (Different issue)
![screen shot 2015-09-20 at 12 44 25 pm](https://cloud.githubusercontent.com/assets/6189453/9982561/5b8c184c-5f95-11e5-85ba-6ad54504d694.png)

**Comment by rxi** [comment]
Interesting.. Does a more standard resolution (for example, 1024x768) work correctly in fullscreen?

**Comment by WetDesertRock** [comment]
How would I set that?

**Comment by WetDesertRock** [comment]
Yeah, standard resolutions seem to work just fine. Tested: 1344x840, 1024x768, 1024x640 and maybe more, forgot.
