### ISSUE TITLE
[help] compiling examples

### ISSUE THREAD

**Issue by ghost** [rxi/juno#8]
Sorry to bother you but I'm having trouble compiling and running the examples both on mac and linux, I'm a rather new to this so try to bare with me. When i run the build script it comes up with lots of fatal errors "SDL/SDL.h: no such file or directory"  also when i run python cembed.py example/particles/main.lua It gives me a bunch of numbers and I'm not sure what to do from there :/ If you could give me a quick walk though of how to run the examples it would be much appreciated :)

**Comment by WetDesertRock** [comment]
You will need to download and install SDL 1.2 https://www.libsdl.org/download-1.2.php
On linux this may be as easy as an `apt-get install` line.

After you have that, run `python build.py` and it should compile from there. You will then be able to run it via ./bin/juno <project>

**Comment by rxi** [comment]
You will need to install the SDL 1.x dev library, python 2.7, and luajit dev library. It already sounds like you have Python. For the rest, assuming you're on Ubuntu, hopefully you should be able to do the following to get them:

```
sudo apt-get install libsdl1.2-dev libluajit-5.1-dev
```

If you're using a different Linux distro you will need to find the equivalent libraries in its package manager.

Once you have everything you should be able to run the `build.py` script, and after a little while you should get an executable in the `bin/` directory.

**Comment by ghost** [comment]
@rxi and @WetDesertRock thanks! is the process the same or similar on mac?

**Comment by WetDesertRock** [comment]
Pretty much, the main difference being you don't have `apt-get`

**Comment by SirSoltex** [comment]
It would seem that SDL doesn't have a dev 1.x library for mac :/

**Comment by SirSoltex** [comment]
@WetDesertRock I'm now getting lots of
src/main.c:12:10: fatal error: 'SDL/SDL.h' file not found
#include <SDL/SDL.h>

I think this is because I'm not sure how to install the devel-lite files

**Comment by ghost** [comment]
@rxi @WetDesertRock well I have gotten rid of half the errors but
now I'm getting lots of
src/main.c:12:10: fatal error: 'SDL/SDL.h' file not found
#include < SDL/SDL.h >

I think this is because I'm not sure how to install the devel-lite files or that i need to add something to the src folder?
This is on osx fyi

**Comment by WetDesertRock** [comment]
My guess is that you didn't install those files correctly. Without access to you machine I couldn't really figure out the exact issue.

Couple things to help me out:
`sdl-config --cflags`

As well as give me the build command output by:
`python build.py verbose`

**Comment by SirSoltex** [comment]
@WetDesertRock build command output: https://gist.github.com/SirSoltex/acfb738bdde6cdcca945

**Comment by WetDesertRock** [comment]
Basically sdl-config is missing, so I have a feeling you didn't install it correctly, or your PATH isn't finding it for some reason. You can do your own googling, but a quick search found this: http://stackoverflow.com/questions/2122519/where-is-sdl-config-installed-on-macos-10-6-snow-leopard

sdl-config tells us where the header files are located as well as other important build settings.

**Comment by SirSoltex** [comment]
@WetDesertRock 
s

**Comment by ghost** [comment]
whoops didn't mean to close this :/

**Comment by ghost** [comment]
@WetDesertRock really weird because i installed the runtime libraries as they told me to (put the sdl.framework into the Macintosh HD library folder) and I also installed it from source, perhaps it has something to do with the fact I'm using El Capitan?

**Comment by ghost** [comment]
@WetDesertRock @rxi yes! got SDL installed thanks to homebrew! now when i run sdl-config --cflags i get: -I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE
also i now get this: https://gist.github.com/SirSoltex/5b0b648681825743b67b when running python build.py verbose. i still however get the src/main.c:12:10: fatal error: 'SDL/SDL.h' file not found
#include < SDL/SDL.h > errors

**Comment by WetDesertRock** [comment]
Uh, what does 
`ls /usr/local/include/SDL`
tell you? It should list off at ton of .h files. If not homebrew messed up.

**Comment by ghost** [comment]
@WetDesertRock it does indeed have a bunch of .h files.

**Comment by WetDesertRock** [comment]
@rxi any ideas? Its getting the right include path, but still not getting the right include path. Verbose command output indicates that the command is getting the right -I flag.

**Comment by ghost** [comment]
I noticed that there is no folder in src (juno/src) called SDL . but if i make one and put the SDL.h file (from /usr/local/include/SDL) in it i get a new error https://gist.github.com/SirSoltex/40b0f12a062c40311abf

**Comment by WetDesertRock** [comment]
Well, that is one way of "fixing" the issue. Just replace all of those occurances of <SDL/SDL.h> with "SDL/SDL.h".

**Comment by ghost** [comment]
@WetDesertRock well it did just the opposite I now get 13 warnings and 16 errors :/ so ill have to revert, any ideas?

**Comment by ghost** [comment]
@WetDesertRock should the -I be in front? (-I/usr/local/include/SDL) wouldn't that invalidate the path - this is in response to the earlier comment when i ran sdl-config --cflags;

**Comment by WetDesertRock** [comment]
Well, maybe you made progress, I don't know without seeing those warnings and errors.

The -I is correct.

**Comment by ghost** [comment]
YES!! It worked it seems when i changed the files to "SDL/SDL.h" i was using a wrong text format so i gave me a bunch of errors, thanks a bunch for the help @WetDesertRock and @rxi
