### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by emekoi** [rxi/juno#9]
How do you embed the scripts into the executable? I've tried to do on my own without success.

**Comment by rxi** [comment]
If you want to package a game's scripts/resources for distribution with the framework, see the following:
https://github.com/rxi/juno/blob/master/doc/packaging.md

If you want to embed .lua scripts (or other files) when compiling the framework, put the script in [src/embed](https://github.com/rxi/juno/tree/master/src/embed). The embedded file's content can then be accessed by including the embedded file's header file which is created by `build.py` at build time.

For example, if you had the file `hello.txt`, to access this you would `#include "hello_txt.h"`, this would declare the variable `hello_txt`: a static const char array (this array is _not_ null-terminated). `sizeof(hello_txt)` can be used to get the file's size.

**Comment by EmekaNkurumeh** [comment]
I mean in a separate project.

**Comment by EmekaNkurumeh** [comment]
Never mind.
